lint:
	npx eslint pages/*.js
	npx eslint components/*.jsx

lint-fix:
	npx eslint --fix pages/*.js
	npx eslint --fix components/*.jsx

run:
	yarn build
	yarn start

build:
	yarn build

start:
	yarn start